# Generated by Django 6.0.2 on 2026-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaire', models.CharField(max_length=50, verbose_name='Horaire')),
                ('type_cours', models.CharField(max_length=20, verbose_name='Type de cours')),
                ('enseignant', models.CharField(max_length=300, verbose_name='Enseignant(s)')),
                ('intitule', models.TextField(verbose_name='Intitulé du cours')),
                ('niveau', models.CharField(max_length=100, verbose_name='Niveau')),
                ('salle', models.CharField(max_length=50, verbose_name='Salle')),
                ('jour', models.DateField(verbose_name='Jour du cours')),
                ('ressource', models.CharField(max_length=100, verbose_name='Ressource (salle principale)')),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['jour', 'horaire'],
            },
        ),
    ]
