# Generated by Django 6.0.2 on 2026-02-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='type_cours',
            field=models.CharField(max_length=100, verbose_name='Type de cours'),
        ),
    ]
